// <auto-generated />
using LinQTraining.LinqExtensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinQTraining.LinQExtensions.Migrations
{
    [DbContext(typeof(LinQContext))]
    partial class LinQContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LinQTraining.LinqExtensions.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Data");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Data 1"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Data 2"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Data 3"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Data 4"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Data 5"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Data 6"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Data 7"
                        },
                        new
                        {
                            Id = 8,
                            Value = "Data 8"
                        },
                        new
                        {
                            Id = 9,
                            Value = "Data 9"
                        },
                        new
                        {
                            Id = 10,
                            Value = "Data 10"
                        },
                        new
                        {
                            Id = 11,
                            Value = "Data 11"
                        },
                        new
                        {
                            Id = 12,
                            Value = "Data 12"
                        },
                        new
                        {
                            Id = 13,
                            Value = "Data 13"
                        },
                        new
                        {
                            Id = 14,
                            Value = "Data 14"
                        },
                        new
                        {
                            Id = 15,
                            Value = "Data 15"
                        },
                        new
                        {
                            Id = 16,
                            Value = "Data 16"
                        },
                        new
                        {
                            Id = 17,
                            Value = "Data 17"
                        },
                        new
                        {
                            Id = 18,
                            Value = "Data 18"
                        },
                        new
                        {
                            Id = 19,
                            Value = "Data 19"
                        },
                        new
                        {
                            Id = 20,
                            Value = "Data 20"
                        },
                        new
                        {
                            Id = 21,
                            Value = "Data 21"
                        },
                        new
                        {
                            Id = 22,
                            Value = "Data 22"
                        },
                        new
                        {
                            Id = 23,
                            Value = "Data 23"
                        },
                        new
                        {
                            Id = 24,
                            Value = "Data 24"
                        },
                        new
                        {
                            Id = 25,
                            Value = "Data 25"
                        },
                        new
                        {
                            Id = 26,
                            Value = "Data 26"
                        },
                        new
                        {
                            Id = 27,
                            Value = "Data 27"
                        },
                        new
                        {
                            Id = 28,
                            Value = "Data 28"
                        },
                        new
                        {
                            Id = 29,
                            Value = "Data 29"
                        },
                        new
                        {
                            Id = 30,
                            Value = "Data 30"
                        },
                        new
                        {
                            Id = 31,
                            Value = "Data 31"
                        },
                        new
                        {
                            Id = 32,
                            Value = "Data 32"
                        },
                        new
                        {
                            Id = 33,
                            Value = "Data 33"
                        },
                        new
                        {
                            Id = 34,
                            Value = "Data 34"
                        },
                        new
                        {
                            Id = 35,
                            Value = "Data 35"
                        },
                        new
                        {
                            Id = 36,
                            Value = "Data 36"
                        },
                        new
                        {
                            Id = 37,
                            Value = "Data 37"
                        },
                        new
                        {
                            Id = 38,
                            Value = "Data 38"
                        },
                        new
                        {
                            Id = 39,
                            Value = "Data 39"
                        },
                        new
                        {
                            Id = 40,
                            Value = "Data 40"
                        },
                        new
                        {
                            Id = 41,
                            Value = "Data 41"
                        },
                        new
                        {
                            Id = 42,
                            Value = "Data 42"
                        },
                        new
                        {
                            Id = 43,
                            Value = "Data 43"
                        },
                        new
                        {
                            Id = 44,
                            Value = "Data 44"
                        },
                        new
                        {
                            Id = 45,
                            Value = "Data 45"
                        },
                        new
                        {
                            Id = 46,
                            Value = "Data 46"
                        },
                        new
                        {
                            Id = 47,
                            Value = "Data 47"
                        },
                        new
                        {
                            Id = 48,
                            Value = "Data 48"
                        },
                        new
                        {
                            Id = 49,
                            Value = "Data 49"
                        },
                        new
                        {
                            Id = 50,
                            Value = "Data 50"
                        },
                        new
                        {
                            Id = 51,
                            Value = "Data 51"
                        },
                        new
                        {
                            Id = 52,
                            Value = "Data 52"
                        },
                        new
                        {
                            Id = 53,
                            Value = "Data 53"
                        },
                        new
                        {
                            Id = 54,
                            Value = "Data 54"
                        },
                        new
                        {
                            Id = 55,
                            Value = "Data 55"
                        },
                        new
                        {
                            Id = 56,
                            Value = "Data 56"
                        },
                        new
                        {
                            Id = 57,
                            Value = "Data 57"
                        },
                        new
                        {
                            Id = 58,
                            Value = "Data 58"
                        },
                        new
                        {
                            Id = 59,
                            Value = "Data 59"
                        },
                        new
                        {
                            Id = 60,
                            Value = "Data 60"
                        },
                        new
                        {
                            Id = 61,
                            Value = "Data 61"
                        },
                        new
                        {
                            Id = 62,
                            Value = "Data 62"
                        },
                        new
                        {
                            Id = 63,
                            Value = "Data 63"
                        },
                        new
                        {
                            Id = 64,
                            Value = "Data 64"
                        },
                        new
                        {
                            Id = 65,
                            Value = "Data 65"
                        },
                        new
                        {
                            Id = 66,
                            Value = "Data 66"
                        },
                        new
                        {
                            Id = 67,
                            Value = "Data 67"
                        },
                        new
                        {
                            Id = 68,
                            Value = "Data 68"
                        },
                        new
                        {
                            Id = 69,
                            Value = "Data 69"
                        },
                        new
                        {
                            Id = 70,
                            Value = "Data 70"
                        },
                        new
                        {
                            Id = 71,
                            Value = "Data 71"
                        },
                        new
                        {
                            Id = 72,
                            Value = "Data 72"
                        },
                        new
                        {
                            Id = 73,
                            Value = "Data 73"
                        },
                        new
                        {
                            Id = 74,
                            Value = "Data 74"
                        },
                        new
                        {
                            Id = 75,
                            Value = "Data 75"
                        },
                        new
                        {
                            Id = 76,
                            Value = "Data 76"
                        },
                        new
                        {
                            Id = 77,
                            Value = "Data 77"
                        },
                        new
                        {
                            Id = 78,
                            Value = "Data 78"
                        },
                        new
                        {
                            Id = 79,
                            Value = "Data 79"
                        },
                        new
                        {
                            Id = 80,
                            Value = "Data 80"
                        },
                        new
                        {
                            Id = 81,
                            Value = "Data 81"
                        },
                        new
                        {
                            Id = 82,
                            Value = "Data 82"
                        },
                        new
                        {
                            Id = 83,
                            Value = "Data 83"
                        },
                        new
                        {
                            Id = 84,
                            Value = "Data 84"
                        },
                        new
                        {
                            Id = 85,
                            Value = "Data 85"
                        },
                        new
                        {
                            Id = 86,
                            Value = "Data 86"
                        },
                        new
                        {
                            Id = 87,
                            Value = "Data 87"
                        },
                        new
                        {
                            Id = 88,
                            Value = "Data 88"
                        },
                        new
                        {
                            Id = 89,
                            Value = "Data 89"
                        },
                        new
                        {
                            Id = 90,
                            Value = "Data 90"
                        },
                        new
                        {
                            Id = 91,
                            Value = "Data 91"
                        },
                        new
                        {
                            Id = 92,
                            Value = "Data 92"
                        },
                        new
                        {
                            Id = 93,
                            Value = "Data 93"
                        },
                        new
                        {
                            Id = 94,
                            Value = "Data 94"
                        },
                        new
                        {
                            Id = 95,
                            Value = "Data 95"
                        },
                        new
                        {
                            Id = 96,
                            Value = "Data 96"
                        },
                        new
                        {
                            Id = 97,
                            Value = "Data 97"
                        },
                        new
                        {
                            Id = 98,
                            Value = "Data 98"
                        },
                        new
                        {
                            Id = 99,
                            Value = "Data 99"
                        },
                        new
                        {
                            Id = 100,
                            Value = "Data 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
