// <auto-generated />
using LinQTraining;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinQTraining.Migrations
{
    [DbContext(typeof(LinQContext))]
    [Migration("20230205151727_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LinQTraining.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = "company1",
                            Name = "company1"
                        },
                        new
                        {
                            Id = "company2",
                            Name = "company2"
                        },
                        new
                        {
                            Id = "company3",
                            Name = "company3"
                        },
                        new
                        {
                            Id = "company4",
                            Name = "company4"
                        },
                        new
                        {
                            Id = "company5",
                            Name = "company5"
                        },
                        new
                        {
                            Id = "company6",
                            Name = "company6"
                        },
                        new
                        {
                            Id = "company7",
                            Name = "company7"
                        },
                        new
                        {
                            Id = "company8",
                            Name = "company8"
                        },
                        new
                        {
                            Id = "company9",
                            Name = "company9"
                        },
                        new
                        {
                            Id = "company10",
                            Name = "company10"
                        },
                        new
                        {
                            Id = "company11",
                            Name = "company11"
                        },
                        new
                        {
                            Id = "company12",
                            Name = "company12"
                        },
                        new
                        {
                            Id = "company13",
                            Name = "company13"
                        },
                        new
                        {
                            Id = "company14",
                            Name = "company14"
                        },
                        new
                        {
                            Id = "company15",
                            Name = "company15"
                        },
                        new
                        {
                            Id = "company16",
                            Name = "company16"
                        },
                        new
                        {
                            Id = "company17",
                            Name = "company17"
                        },
                        new
                        {
                            Id = "company18",
                            Name = "company18"
                        },
                        new
                        {
                            Id = "company19",
                            Name = "company19"
                        },
                        new
                        {
                            Id = "company20",
                            Name = "company20"
                        },
                        new
                        {
                            Id = "company21",
                            Name = "company21"
                        },
                        new
                        {
                            Id = "company22",
                            Name = "company22"
                        },
                        new
                        {
                            Id = "company23",
                            Name = "company23"
                        },
                        new
                        {
                            Id = "company24",
                            Name = "company24"
                        },
                        new
                        {
                            Id = "company25",
                            Name = "company25"
                        },
                        new
                        {
                            Id = "company26",
                            Name = "company26"
                        },
                        new
                        {
                            Id = "company27",
                            Name = "company27"
                        },
                        new
                        {
                            Id = "company28",
                            Name = "company28"
                        },
                        new
                        {
                            Id = "company29",
                            Name = "company29"
                        },
                        new
                        {
                            Id = "company30",
                            Name = "company30"
                        },
                        new
                        {
                            Id = "company31",
                            Name = "company31"
                        },
                        new
                        {
                            Id = "company32",
                            Name = "company32"
                        },
                        new
                        {
                            Id = "company33",
                            Name = "company33"
                        },
                        new
                        {
                            Id = "company34",
                            Name = "company34"
                        },
                        new
                        {
                            Id = "company35",
                            Name = "company35"
                        },
                        new
                        {
                            Id = "company36",
                            Name = "company36"
                        },
                        new
                        {
                            Id = "company37",
                            Name = "company37"
                        },
                        new
                        {
                            Id = "company38",
                            Name = "company38"
                        },
                        new
                        {
                            Id = "company39",
                            Name = "company39"
                        },
                        new
                        {
                            Id = "company40",
                            Name = "company40"
                        },
                        new
                        {
                            Id = "company41",
                            Name = "company41"
                        },
                        new
                        {
                            Id = "company42",
                            Name = "company42"
                        },
                        new
                        {
                            Id = "company43",
                            Name = "company43"
                        },
                        new
                        {
                            Id = "company44",
                            Name = "company44"
                        },
                        new
                        {
                            Id = "company45",
                            Name = "company45"
                        },
                        new
                        {
                            Id = "company46",
                            Name = "company46"
                        },
                        new
                        {
                            Id = "company47",
                            Name = "company47"
                        },
                        new
                        {
                            Id = "company48",
                            Name = "company48"
                        },
                        new
                        {
                            Id = "company49",
                            Name = "company49"
                        },
                        new
                        {
                            Id = "company50",
                            Name = "company50"
                        },
                        new
                        {
                            Id = "company51",
                            Name = "company51"
                        },
                        new
                        {
                            Id = "company52",
                            Name = "company52"
                        },
                        new
                        {
                            Id = "company53",
                            Name = "company53"
                        },
                        new
                        {
                            Id = "company54",
                            Name = "company54"
                        },
                        new
                        {
                            Id = "company55",
                            Name = "company55"
                        },
                        new
                        {
                            Id = "company56",
                            Name = "company56"
                        },
                        new
                        {
                            Id = "company57",
                            Name = "company57"
                        },
                        new
                        {
                            Id = "company58",
                            Name = "company58"
                        },
                        new
                        {
                            Id = "company59",
                            Name = "company59"
                        },
                        new
                        {
                            Id = "company60",
                            Name = "company60"
                        },
                        new
                        {
                            Id = "company61",
                            Name = "company61"
                        },
                        new
                        {
                            Id = "company62",
                            Name = "company62"
                        },
                        new
                        {
                            Id = "company63",
                            Name = "company63"
                        },
                        new
                        {
                            Id = "company64",
                            Name = "company64"
                        },
                        new
                        {
                            Id = "company65",
                            Name = "company65"
                        },
                        new
                        {
                            Id = "company66",
                            Name = "company66"
                        },
                        new
                        {
                            Id = "company67",
                            Name = "company67"
                        },
                        new
                        {
                            Id = "company68",
                            Name = "company68"
                        },
                        new
                        {
                            Id = "company69",
                            Name = "company69"
                        },
                        new
                        {
                            Id = "company70",
                            Name = "company70"
                        },
                        new
                        {
                            Id = "company71",
                            Name = "company71"
                        },
                        new
                        {
                            Id = "company72",
                            Name = "company72"
                        },
                        new
                        {
                            Id = "company73",
                            Name = "company73"
                        },
                        new
                        {
                            Id = "company74",
                            Name = "company74"
                        },
                        new
                        {
                            Id = "company75",
                            Name = "company75"
                        },
                        new
                        {
                            Id = "company76",
                            Name = "company76"
                        },
                        new
                        {
                            Id = "company77",
                            Name = "company77"
                        },
                        new
                        {
                            Id = "company78",
                            Name = "company78"
                        },
                        new
                        {
                            Id = "company79",
                            Name = "company79"
                        },
                        new
                        {
                            Id = "company80",
                            Name = "company80"
                        },
                        new
                        {
                            Id = "company81",
                            Name = "company81"
                        },
                        new
                        {
                            Id = "company82",
                            Name = "company82"
                        },
                        new
                        {
                            Id = "company83",
                            Name = "company83"
                        },
                        new
                        {
                            Id = "company84",
                            Name = "company84"
                        },
                        new
                        {
                            Id = "company85",
                            Name = "company85"
                        },
                        new
                        {
                            Id = "company86",
                            Name = "company86"
                        },
                        new
                        {
                            Id = "company87",
                            Name = "company87"
                        },
                        new
                        {
                            Id = "company88",
                            Name = "company88"
                        },
                        new
                        {
                            Id = "company89",
                            Name = "company89"
                        },
                        new
                        {
                            Id = "company90",
                            Name = "company90"
                        },
                        new
                        {
                            Id = "company91",
                            Name = "company91"
                        },
                        new
                        {
                            Id = "company92",
                            Name = "company92"
                        },
                        new
                        {
                            Id = "company93",
                            Name = "company93"
                        },
                        new
                        {
                            Id = "company94",
                            Name = "company94"
                        },
                        new
                        {
                            Id = "company95",
                            Name = "company95"
                        },
                        new
                        {
                            Id = "company96",
                            Name = "company96"
                        },
                        new
                        {
                            Id = "company97",
                            Name = "company97"
                        },
                        new
                        {
                            Id = "company98",
                            Name = "company98"
                        },
                        new
                        {
                            Id = "company99",
                            Name = "company99"
                        },
                        new
                        {
                            Id = "company100",
                            Name = "company100"
                        },
                        new
                        {
                            Id = "company101",
                            Name = "company101"
                        },
                        new
                        {
                            Id = "company102",
                            Name = "company102"
                        },
                        new
                        {
                            Id = "company103",
                            Name = "company103"
                        },
                        new
                        {
                            Id = "company104",
                            Name = "company104"
                        },
                        new
                        {
                            Id = "company105",
                            Name = "company105"
                        },
                        new
                        {
                            Id = "company106",
                            Name = "company106"
                        },
                        new
                        {
                            Id = "company107",
                            Name = "company107"
                        },
                        new
                        {
                            Id = "company108",
                            Name = "company108"
                        },
                        new
                        {
                            Id = "company109",
                            Name = "company109"
                        },
                        new
                        {
                            Id = "company110",
                            Name = "company110"
                        },
                        new
                        {
                            Id = "company111",
                            Name = "company111"
                        },
                        new
                        {
                            Id = "company112",
                            Name = "company112"
                        },
                        new
                        {
                            Id = "company113",
                            Name = "company113"
                        },
                        new
                        {
                            Id = "company114",
                            Name = "company114"
                        },
                        new
                        {
                            Id = "company115",
                            Name = "company115"
                        },
                        new
                        {
                            Id = "company116",
                            Name = "company116"
                        },
                        new
                        {
                            Id = "company117",
                            Name = "company117"
                        },
                        new
                        {
                            Id = "company118",
                            Name = "company118"
                        },
                        new
                        {
                            Id = "company119",
                            Name = "company119"
                        },
                        new
                        {
                            Id = "company120",
                            Name = "company120"
                        },
                        new
                        {
                            Id = "company121",
                            Name = "company121"
                        },
                        new
                        {
                            Id = "company122",
                            Name = "company122"
                        },
                        new
                        {
                            Id = "company123",
                            Name = "company123"
                        },
                        new
                        {
                            Id = "company124",
                            Name = "company124"
                        },
                        new
                        {
                            Id = "company125",
                            Name = "company125"
                        },
                        new
                        {
                            Id = "company126",
                            Name = "company126"
                        },
                        new
                        {
                            Id = "company127",
                            Name = "company127"
                        },
                        new
                        {
                            Id = "company128",
                            Name = "company128"
                        },
                        new
                        {
                            Id = "company129",
                            Name = "company129"
                        },
                        new
                        {
                            Id = "company130",
                            Name = "company130"
                        },
                        new
                        {
                            Id = "company131",
                            Name = "company131"
                        },
                        new
                        {
                            Id = "company132",
                            Name = "company132"
                        },
                        new
                        {
                            Id = "company133",
                            Name = "company133"
                        },
                        new
                        {
                            Id = "company134",
                            Name = "company134"
                        },
                        new
                        {
                            Id = "company135",
                            Name = "company135"
                        },
                        new
                        {
                            Id = "company136",
                            Name = "company136"
                        },
                        new
                        {
                            Id = "company137",
                            Name = "company137"
                        },
                        new
                        {
                            Id = "company138",
                            Name = "company138"
                        },
                        new
                        {
                            Id = "company139",
                            Name = "company139"
                        },
                        new
                        {
                            Id = "company140",
                            Name = "company140"
                        },
                        new
                        {
                            Id = "company141",
                            Name = "company141"
                        },
                        new
                        {
                            Id = "company142",
                            Name = "company142"
                        },
                        new
                        {
                            Id = "company143",
                            Name = "company143"
                        },
                        new
                        {
                            Id = "company144",
                            Name = "company144"
                        },
                        new
                        {
                            Id = "company145",
                            Name = "company145"
                        },
                        new
                        {
                            Id = "company146",
                            Name = "company146"
                        },
                        new
                        {
                            Id = "company147",
                            Name = "company147"
                        },
                        new
                        {
                            Id = "company148",
                            Name = "company148"
                        },
                        new
                        {
                            Id = "company149",
                            Name = "company149"
                        },
                        new
                        {
                            Id = "company150",
                            Name = "company150"
                        },
                        new
                        {
                            Id = "company151",
                            Name = "company151"
                        },
                        new
                        {
                            Id = "company152",
                            Name = "company152"
                        },
                        new
                        {
                            Id = "company153",
                            Name = "company153"
                        },
                        new
                        {
                            Id = "company154",
                            Name = "company154"
                        },
                        new
                        {
                            Id = "company155",
                            Name = "company155"
                        },
                        new
                        {
                            Id = "company156",
                            Name = "company156"
                        },
                        new
                        {
                            Id = "company157",
                            Name = "company157"
                        },
                        new
                        {
                            Id = "company158",
                            Name = "company158"
                        },
                        new
                        {
                            Id = "company159",
                            Name = "company159"
                        },
                        new
                        {
                            Id = "company160",
                            Name = "company160"
                        },
                        new
                        {
                            Id = "company161",
                            Name = "company161"
                        },
                        new
                        {
                            Id = "company162",
                            Name = "company162"
                        },
                        new
                        {
                            Id = "company163",
                            Name = "company163"
                        },
                        new
                        {
                            Id = "company164",
                            Name = "company164"
                        },
                        new
                        {
                            Id = "company165",
                            Name = "company165"
                        },
                        new
                        {
                            Id = "company166",
                            Name = "company166"
                        },
                        new
                        {
                            Id = "company167",
                            Name = "company167"
                        },
                        new
                        {
                            Id = "company168",
                            Name = "company168"
                        },
                        new
                        {
                            Id = "company169",
                            Name = "company169"
                        },
                        new
                        {
                            Id = "company170",
                            Name = "company170"
                        },
                        new
                        {
                            Id = "company171",
                            Name = "company171"
                        },
                        new
                        {
                            Id = "company172",
                            Name = "company172"
                        },
                        new
                        {
                            Id = "company173",
                            Name = "company173"
                        },
                        new
                        {
                            Id = "company174",
                            Name = "company174"
                        },
                        new
                        {
                            Id = "company175",
                            Name = "company175"
                        },
                        new
                        {
                            Id = "company176",
                            Name = "company176"
                        },
                        new
                        {
                            Id = "company177",
                            Name = "company177"
                        },
                        new
                        {
                            Id = "company178",
                            Name = "company178"
                        },
                        new
                        {
                            Id = "company179",
                            Name = "company179"
                        },
                        new
                        {
                            Id = "company180",
                            Name = "company180"
                        },
                        new
                        {
                            Id = "company181",
                            Name = "company181"
                        },
                        new
                        {
                            Id = "company182",
                            Name = "company182"
                        },
                        new
                        {
                            Id = "company183",
                            Name = "company183"
                        },
                        new
                        {
                            Id = "company184",
                            Name = "company184"
                        },
                        new
                        {
                            Id = "company185",
                            Name = "company185"
                        },
                        new
                        {
                            Id = "company186",
                            Name = "company186"
                        },
                        new
                        {
                            Id = "company187",
                            Name = "company187"
                        },
                        new
                        {
                            Id = "company188",
                            Name = "company188"
                        },
                        new
                        {
                            Id = "company189",
                            Name = "company189"
                        },
                        new
                        {
                            Id = "company190",
                            Name = "company190"
                        },
                        new
                        {
                            Id = "company191",
                            Name = "company191"
                        },
                        new
                        {
                            Id = "company192",
                            Name = "company192"
                        },
                        new
                        {
                            Id = "company193",
                            Name = "company193"
                        },
                        new
                        {
                            Id = "company194",
                            Name = "company194"
                        },
                        new
                        {
                            Id = "company195",
                            Name = "company195"
                        },
                        new
                        {
                            Id = "company196",
                            Name = "company196"
                        },
                        new
                        {
                            Id = "company197",
                            Name = "company197"
                        },
                        new
                        {
                            Id = "company198",
                            Name = "company198"
                        },
                        new
                        {
                            Id = "company199",
                            Name = "company199"
                        },
                        new
                        {
                            Id = "company200",
                            Name = "company200"
                        });
                });

            modelBuilder.Entity("LinQTraining.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = "fruit",
                            CompanyId = "company1",
                            Name = "apple"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = "fruit",
                            CompanyId = "company1",
                            Name = "banana"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = "fruit",
                            CompanyId = "company1",
                            Name = "orange"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = "fruit",
                            CompanyId = "company1",
                            Name = "grape"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = "fruit",
                            CompanyId = "company2",
                            Name = "mango"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = "electronic",
                            CompanyId = "company2",
                            Name = "television"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = "electronic",
                            CompanyId = "company2",
                            Name = "laptop"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = "electronic",
                            CompanyId = "company2",
                            Name = "keyboard"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = "electronic",
                            CompanyId = "company2",
                            Name = "monitor"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = "household",
                            CompanyId = "company3",
                            Name = "knife"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = "household",
                            CompanyId = "company3",
                            Name = "spoon"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = "household",
                            CompanyId = "company3",
                            Name = "bowl"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = "household",
                            CompanyId = "company3",
                            Name = "chopsticks"
                        });
                });

            modelBuilder.Entity("LinQTraining.ProductCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = "fruit",
                            CompanyId = "company1",
                            Name = "fruit"
                        },
                        new
                        {
                            Id = "electronic",
                            CompanyId = "company2",
                            Name = "electronic"
                        },
                        new
                        {
                            Id = "household",
                            CompanyId = "company2",
                            Name = "household"
                        },
                        new
                        {
                            Id = "misc",
                            CompanyId = "company3",
                            Name = "misc"
                        });
                });

            modelBuilder.Entity("LinQTraining.Product", b =>
                {
                    b.HasOne("LinQTraining.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("LinQTraining.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LinQTraining.ProductCategory", b =>
                {
                    b.HasOne("LinQTraining.Company", "Company")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LinQTraining.Company", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("LinQTraining.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
